# gcloud app deploy --project datablue --version 1
runtime: python39
entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 2

handlers:
- url: /.*
  script: main.app
