# gcloud app deploy --project datablue --version 1
runtime: go121

env_variables:
  NETRECEIVER_CREDENTIALS: gs://ausocean/NetReceiver-55f1f53a6d8a.json
  VIDGRIND_CREDENTIALS: gs://ausocean/VideoGrinder-b0ad82abac05.json

handlers:
- url: /.*
  script: auto
